version: '3'
services:
  api:
    container_name: buy-in-usa.api
    build: .
    command: streamlit run main.py
    ports:
      - "8501:8501"
    volumes:
      - "./:/app"
    tty: true
    stdin_open: true